
with(DETools);
ecdif1 := diff(x(t), t) = x(t) + 4*y(t);
ecdif2 := diff(y(t), t) = x(t) + y(t);
sist := ecdif1, ecdif2;
sol := dsolve({sist}, {x(t), y(t)});
xx := unapply(rhs(sol[1]), t, c__1, c__2);
yy := unapply(rhs(sol[2]), t, c__1, c__2);
plot([xx(t, 1, 1), yy(t, 1, 1)], t = -10 .. 10, color = [red, blue]);
restart;
with(DETools);
ecdif1 := diff(x(t), t) = 2*x(t) - y(t);
ecdif2 := diff(y(t), t) = x(t) + 2*y(t);
sist := ecdif1, ecdif2;
sol := dsolve({sist}, {x(t), y(t)});
xx := unapply(rhs(sol[1]), t, c__1, c__2);
yy := unapply(rhs(sol[2]), t, c__1, c__2);
plot([xx(t, 1, 1), yy(t, 1, 1)], t = -2 .. 2, color = [red, blue]);
restart;
with(DETools);
ecdif1 := diff(x(t), t) = x(t) + 4*y(t);
ecdif2 := diff(y(t), t) = x(t) + y(t);
cond_in := x(0) = 1, y(0) = 2;
sist := ecdif1, ecdif2;
sol := dsolve({cond_in, sist}, {x(t), y(t)});
xx := unapply(rhs(sol[1]), t);
yy := unapply(rhs(sol[2]), t);
plot([xx(t), yy(t)], t = -2 .. 2, color = [red, blue]);
restart;
with(DETools);
ecdif1 := diff(x(t), t) = x(t) - y(t) + t - 1;
ecdif2 := diff(y(t), t) = -2*x(t) + y(t) + 1;
cond_in := x(0) = 0, y(0) = 1;
sist := ecdif1, ecdif2;
sol := dsolve({cond_in, sist}, {x(t), y(t)});
xx := unapply(rhs(sol[1]), t);
yy := unapply(rhs(sol[2]), t);
plot([xx(t), yy(t)], t = -2 .. 2, color = [red, blue]);
restart;
with(DETools);
ecdif1 := diff(x(t), t) = y(t);
ecdif2 := diff(y(t), t) = -x(t) - 2*y(t);
sist := ecdif1, ecdif2;
sol := dsolve({sist}, {x(t), y(t)});
xx := unapply(rhs(sol[1]), t, c__1, c__2);
yy := unapply(rhs(sol[2]), t, c__1, c__2);
eval(limit(xx(t, c__1, c__2), t = infinity));
eval(limit(yy(t, c__1, c__2), t = infinity));
DEplot([sist], [x(t), y(t)], t = -4 .. 4, x = -10 .. 10, y = -10 .. 10, [[x(0) = 1, y(0) = 1], [x(0) = 1, y(0) = 5]], arrows = medium, linecolor = blue);
restart;
with(DETools);
ecdif1 := diff(x(t), t) = 2*x(t) + y(t);
ecdif2 := diff(y(t), t) = x(t) + 2*y(t);
sist := ecdif1, ecdif2;
cond_in2 := [x(0) = 0, y(0) = 1], [x(0) = 0, y(0) = 2], [x(0) = 0, y(0) = 3], [x(0) = 0, y(0) = 4], [x(0) = 0, y(0) = 5], [x(0) = 0, y(0) = -1], [x(0) = 0, y(0) = -2], [x(0) = 0, y(0) = -3], [x(0) = 0, y(0) = -4], [x(0) = 0, y(0) = -5], [x(0) = 1, y(0) = 0], [x(0) = 2, y(0) = 0], [x(0) = 3, y(0) = 0], [x(0) = 4, y(0) = 0], [x(0) = 5, y(0) = 0], [x(0) = -1, y(0) = 0], [x(0) = -2, y(0) = 0], [x(0) = -3, y(0) = 0], [x(0) = -4, y(0) = 0], [x(0) = -5, y(0) = 0];
DEplot([sist], [x(t), y(t)], t = -5 .. 5, x = -10 .. 10, y = -10 .. 10, [cond_in2], arrows = medium, linecolor = blue, stepsize = 0.1);
restart;
with(DETools);
ecdif1 := diff(x(t), t) = y(t);
ecdif2 := diff(y(t), t) = -x(t);
sist := ecdif1, ecdif2;
cond_in2 := [x(0) = 0, y(0) = 1], [x(0) = 0, y(0) = 2], [x(0) = 0, y(0) = 3], [x(0) = 0, y(0) = 4], [x(0) = 0, y(0) = 5], [x(0) = 0, y(0) = -1], [x(0) = 0, y(0) = -2], [x(0) = 0, y(0) = -3], [x(0) = 0, y(0) = -4], [x(0) = 0, y(0) = -5], [x(0) = 1, y(0) = 0], [x(0) = 2, y(0) = 0], [x(0) = 3, y(0) = 0], [x(0) = 4, y(0) = 0], [x(0) = 5, y(0) = 0], [x(0) = -1, y(0) = 0], [x(0) = -2, y(0) = 0], [x(0) = -3, y(0) = 0], [x(0) = -4, y(0) = 0], [x(0) = -5, y(0) = 0];
DEplot([sist], [x(t), y(t)], t = -5 .. 5, x = -10 .. 10, y = -10 .. 10, [cond_in2], arrows = medium, linecolor = blue, stepsize = 0.1);
NULL;
restart;
with(DETools);
ecdif1 := diff(x(t), t) = -x(t) - y(t);
ecdif2 := diff(y(t), t) = x(t) - y(t);
sist := ecdif1, ecdif2;
cond_in2 := [x(0) = 0, y(0) = 1], [x(0) = 0, y(0) = 2], [x(0) = 0, y(0) = 3], [x(0) = 0, y(0) = 4], [x(0) = 0, y(0) = 5], [x(0) = 0, y(0) = -1], [x(0) = 0, y(0) = -2], [x(0) = 0, y(0) = -3], [x(0) = 0, y(0) = -4], [x(0) = 0, y(0) = -5], [x(0) = 1, y(0) = 0], [x(0) = 2, y(0) = 0], [x(0) = 3, y(0) = 0], [x(0) = 4, y(0) = 0], [x(0) = 5, y(0) = 0], [x(0) = -1, y(0) = 0], [x(0) = -2, y(0) = 0], [x(0) = -3, y(0) = 0], [x(0) = -4, y(0) = 0], [x(0) = -5, y(0) = 0];
DEplot([sist], [x(t), y(t)], t = -5 .. 5, x = -10 .. 10, y = -10 .. 10, [cond_in2], arrows = medium, linecolor = blue, stepsize = 0.1);
restart;
with(DETools);
ecdif1 := diff(x(t), t) = -2*x(t);
ecdif2 := diff(y(t), t) = -4*x(t) - 2*y(t);
sist := ecdif1, ecdif2;
cond_in2 := [x(0) = 0, y(0) = 1], [x(0) = 0, y(0) = 2], [x(0) = 0, y(0) = 3], [x(0) = 0, y(0) = 4], [x(0) = 0, y(0) = 5], [x(0) = 0, y(0) = -1], [x(0) = 0, y(0) = -2], [x(0) = 0, y(0) = -3], [x(0) = 0, y(0) = -4], [x(0) = 0, y(0) = -5], [x(0) = 1, y(0) = 0], [x(0) = 2, y(0) = 0], [x(0) = 3, y(0) = 0], [x(0) = 4, y(0) = 0], [x(0) = 5, y(0) = 0], [x(0) = -1, y(0) = 0], [x(0) = -2, y(0) = 0], [x(0) = -3, y(0) = 0], [x(0) = -4, y(0) = 0], [x(0) = -5, y(0) = 0];
DEplot([sist], [x(t), y(t)], t = -5 .. 5, x = -10 .. 10, y = -10 .. 10, [cond_in2], arrows = medium, linecolor = blue, stepsize = 0.1);
restart;
with(DETools);
ecdif1 := diff(x(t), t) = x(t) - y(t) + z(t);
ecdif2 := diff(y(t), t) = x(t) + y(t) - z(t);
ecdif3 := diff(z(t), t) = -y(t) + 2*z(t);
sist := ecdif1, ecdif2, ecdif3;
sol := dsolve({sist}, {x(t), y(t), z(t)});
xx := unapply(rhs(sol[1]), t, c__1, c__2, c__3);
yy := unapply(rhs(sol[2]), t, c__1, c__2, c__3);
zz := unapply(rhs(sol[3]), t, c__1, c__2, c__3);
plot([xx(t, 1, 1, 1), yy(t, 1, 1, 1), zz(t, 1, 1, 1)], t = -5 .. 5, color = [red, blue, green]);
restart;
with(DETools);
ecdif1 := diff(x(t), t) = 5*x(t) + 3*y(t) + 1;
ecdif2 := diff(y(t), t) = -6*x(t) - 4*y(t) + exp(-t);
sist := ecdif1, ecdif2;
sol := dsolve({sist}, {x(t), y(t)});
xx := unapply(rhs(sol[1]), t, c__1, c__2);
yy := unapply(rhs(sol[2]), t, c__1, c__2);
plot([xx(t, 1, 1), yy(t, 1, 1)], t = -4 .. 4, color = [red, blue]);
restart;
with(DETools);
ecdif1 := diff(x(t), t) = x(t) + 2*y(t) + 1;
ecdif2 := diff(y(t), t) = -2*x(t) + 4*y(t) + cos(t);
cond_in := x(0) = 0, y(0) = 1;
sist := ecdif1, ecdif2;
sol := dsolve({cond_in, sist}, {x(t), y(t)});
xx := unapply(rhs(sol[1]), t);
yy := unapply(rhs(sol[2]), t);
plot([xx(t), yy(t)], t = -5 .. 5, color = [red, blue]);
NULL;
