
(12 + 4) - 5;
2^10;
sin(0.1);
(a + b)(a - b);
f := x -> 3*x^3 + 2*x^2 - 5;
diff(f(x), x);
f := x -> sqrt(1 + x^4);
diff(f(x), x);
f := x -> exp(x)*sin(x)*cos(x);
diff(f(x), x);
simplify((a + b)(a - b));
expand((a + b)*(a - b));
simplify((a + b)*(a - b));
int(3*x^3 + 2*x^2 - 5, x = 0 .. 1);
int(1/x^2, x = 0 .. infinity);
int(exp(-x^2), x = -infinity .. infinity);
limit(sin(x)/x, x = 0);
limit((x^3 + 3*x^2 - 5)/(2*x^3 - 7*x), x = infinity);
limit((cos(x) + 1)/(x - Pi), x = Pi);
f := x -> exp(-x) - 1;
with(plots);
plot(f(x), x = -2 .. 2);
f := (x, r) -> 200*exp(r*x)/(2*exp(r*x) + 98);
with(plots);
plot([f(x, 0.5), f(x, -0.5)], x = 0 .. 50), color = [red, blue];
f := x -> x*sin(1/x);
with(plots);
plot(f(x), x = -3 .. 3);
with(plots);
plot([1 - cos(t)*cos(t), (1 - cos(t))*sin(t), t = 0 .. 2*Pi]);
with(plots);
plot([sin(3*t)*cos(t), sin(3*t)*sin(t), t = 0 .. 2*Pi]);
with(plots);
plot([t - sin(t), 1 - cos(t), t = 0 .. 6*Pi]);
f := (t, s) -> 1 - s*cos(4*t)*cos(t)/sqrt(1 - s^2*cos(4*t)^2*sin(t)^2);
x := (t, s) -> f(t - 1/2*Pi, s);
y := (t, s) -> f(t, s);
list_xy := [x(t, s/10), y(t, s/10), t = 0 .. 2*Pi] $ (s = 1 .. 10);
plot([list_xy]);
with(plots);
implicitplot(x^2 + y^2 - 2*x - 4*y + 4 = 0);
with(plots);
implicitplot((x - y)^2 - 2*y^2 = 1);
z := (x, y) -> 4*x^2*exp(y) - 2*x^4 - exp(4*y);
with(plots);
plot3d(z(x, y), x = -3 .. 3, y = -1 .. 1, axes = boxed);
z := (x, y) -> 4*x^2 - y^2;
with(plots);
plot3d(z(x, y), x = -100 .. 100, y = -100 .. 100, axes = boxed);
with(linalg);
A := matrix([[1, 2, -1], [0, 1, 0], [3, -1, 2]]);
B := matrix([[1, 2, 3], [1, 1, 2], [2, 1, 1]]);
C := matrix([[2, 1, 1], [0, 1, -1], [4, 2, 2]]);
evalm(2*A - (B &* C));
evalm(1/A);
eigenvects(C);
eigenvals(C);
NULL;
