
with(DEtools);
ecdif := diff(y(x), x) = 2*x*(1 + y(x)^2);
dsolve(ecdif, y(x));
y1 := (x, c) -> tan(x^2 + 2*c);
with(plots);
plot(y1(x, 1), x = -infinity .. infinity);
y1 := (x, c) -> tan(x^2 + 2*c);
with(plots);
plot(y1(x, 314/100), x = -infinity .. infinity);
with(DEtools);
ecdif := (x^2 - 1)*diff(y(x), x) + 2*x*y(x)^2 = 0;
dsolve(ecdif, y(x));
y1 := (x, c) -> 1/(ln(x - 1) + ln(x + 1) + c);
with(plots);
plot(y1(x, 1), x = 2 .. 10);
plot(y1(x, 10), x = 2 .. 10);
with(DEtools);
ecdif := 2*x^2*diff(y(x), x) = x^2 + y(x)^2;
dsolve(ecdif, y(x));
y1 := (x, c) -> x*(ln(x) + c - 2)/(ln(x) + c);
with(plots);
plot(y1(x, 1), x = 2 .. 10);
with(DEtools);
ecdif := diff(y(x), x) = -x/y(x);
dsolve(ecdif, y(x));
y1 := (x, c) -> sqrt(-x^2 + c);
with(plots);
plot(y1(x, 100), x = 2 .. 9);
plot(y1(x, 10), x = 1 .. 3);
NULL;
y2 := (x, c) -> -sqrt(-x^2 + c);
with(plots);
plot(y2(x, 100), x = 2 .. 9);
NULL;
y2 := (x, c) -> -sqrt(-x^2 + c);
with(plots);
plot(y2(x, 10), x = 1 .. 3);
NULL;
with(DEtools);
ecdif := diff(y(x), x) = -x/y(x)^3;
dsolve(ecdif, y(x));
y1 := (x, c) -> (-2*x^2 + c)^(1/4);
with(plots);
plot([y1(x, 20), y1(x, 10)], x = 1 .. 3);
with(DEtools);
ecdif := diff(y(x), x) + y(x)*tan(x) = 1/cos(x);
dsolve(ecdif, y(x));
y1 := (x, c) -> (tan(x) + c)*cos(x);
with(plots);
plot([y1(x, 10), y1(x, 5)], x = 0 .. 10);
with(DEtools);
ecdif := diff(y(x), x) = -(x + y(x))/y(x);
dsolve(ecdif, y(x));
soll := dsolve(ecdif, y(x));
right_hand_expr := rhs(soll);
y1 := unapply(right_hand_expr, x, _C1);
plot([y1(x, 10), y1(x, 3)], x = 0 .. 2);
with(DEtools);
ecdif := diff(y(x), x) + 2*y(x)/x = x^3;
dsolve(ecdif, y(x));
y1 := (x, c) -> (1/6*x^6 + c)/x^2;
with(plots);
plot([y1(x, 10), y1(x, 2), x = 1 .. 3]);
with(DETools);
ecdif := diff(y(x), x) - 1/2*y(x) = cos(x);
DEplot(ecdif, y(x), x = -1 .. 1, y = -1 .. 3, stepsize = 0.1);
DEplot(ecdif, y(x), x = -10 .. 10, y = -100 .. 100, stepsize = 0.1);
soll := dsolve(ecdif, y(x));
right_hand_side := rhs(soll);
y1 := unapply(right_hand_side, x, c);
DEplot(ecdif, y(x), x = -5 .. 5, y = -10 .. 10, [[y(0) = -2], [y(0) = 2], [y(0) = -2/5]], stepsize = 0.1, linecolor = [black, red, blue]);
with(DETools);
ecdif := diff(y(x), x, x) + y(x) = sin(x) + cos(x);
soll := dsolve(ecdif, y(x));
right_hand_side := rhs(soll);
y1 := unapply(right_hand_side, x, c__1, c__2);
plot([y1(x, 0, 0), y1(x, 0, 1), y1(x, 1, 0), y1(x, 1, 1)], x = -10 .. 10, y = -10 .. 10);
with(DETools);
ecdif := diff(y(x), x, x) - 5*diff(y(x), x) + 4*y(x) = 0;
soll := dsolve(ecdif, y(x));
right_hand_side := rhs(soll);
y1 := unapply(right_hand_side, x, c__1, c__2);

cond_in := y(0) = 5, D(y)(0) = 8;
soll_1 := dsolve({cond_in, ecdif}, y(x));
right_hand_side__1 := rhs(soll_1);
y2 := unapply(right_hand_side__1, x);
plot(y2(x), x = 10 .. -10, y = -10 .. 10);
restart;
with(DETools);
ecdif := diff(y(x), x, x) - diff(y(x), x) - 2*y(x) = 0;
cond_in := y(0) = a, D(y)(0) = 2;
soll := dsolve({cond_in, ecdif}, y(x));
limit(soll, x = infinity);
restart;
with(DETools);
ecdif := diff(y(x), x) + k*y(x)/x = x^3;
soll := dsolve(ecdif, y(x));
right_hand_side := rhs(soll);
y1 := unapply(right_hand_side, x, k, c__1);
list_f := y1(x, 1, i) $ (i = 1 .. 10);
plot([list_f], x = -1 .. 1);
ecdif2 := diff(y(x), x) + y(x)/x = x^3;
soll_2 := dsolve(ecdif2);
DEplot(ecdif2, y(x), x = -10 .. 10, y = -10 .. 10);
cond_in := y(1) = 0;
soll_c := dsolve({cond_in, ecdif2}, y(x));
right_hand_side_c := rhs(soll_c);
y_c := unapply(right_hand_side_c, x);
plot(y_c(x), x = -10 .. 10);
ecdif2 := diff(y(x), x) + k*y(x)/x = x^3;
soll_d := dsolve({cond_in, ecdif2}, y(x));
right_hand_side_d := rhs(soll_d);
y_d := unapply(right_hand_side_d, x, k);
list_d := y_d(x, i) $ (i = 1 .. 10);
NULL;
