
with(DETools);
ecdif1 := diff(y(x), x) = 2*x*(1 + y(x)^2);
soll := dsolve(ecdif1, y(x));
y1 := unapply(rhs(soll), x, c__1);
plot(y1(x, 5), x = -10 .. 10);
restart;
with(DETools);
ecdif := (x^2 - 1)*diff(y(x), x) + 2*x*y(x)^2 = 0;
soll := dsolve(ecdif, y(x));
y1 := unapply(rhs(soll), x, c__1);
plot([y1(x, 5), y1(x, 0), y1(x, 1)], x = 3 .. 10, color = [red, green, blue]);
restart;
with(DETools);
ecdif := 2*x^2*diff(y(x), x) = x^2 + y(x)^2;
soll := dsolve(ecdif, y(x));
y1 := unapply(rhs(soll), x, c__1);
plot([y1(x, 1), y1(x, 0), y1(x, 10)], x = 2 .. 10, color = [red, green, blue]);
restart;
with(DETools);
ecdif := diff(y(x), x) = -x/y(x);
soll := dsolve(ecdif, y(x));
y1 := unapply(rhs(soll[1]), x, c__1);
y2 := unapply(rhs(soll[2]), x, c__1);
plot([y1(x, 10), y1(x, 100), y2(x, 10), y2(x, 100)], x = 1 .. 10, color = [red, blue, green, yellow]);
restart;
with(DETools);
ecdif := diff(y(x), x) = -x/y(x)^3;
soll := dsolve(ecdif, y(x));
y1 := unapply(rhs(soll[1]), x, c__1);
y2 := unapply(rhs(soll[2]), x, c__1);
y3 := unapply(rhs(soll[3]), x, c__1);
y4 := unapply(rhs(soll[4]), x, c__1);
plot([y1(x, 10), y2(x, 10), y3(x, 10), y4(x, 10)], x = -10 .. 10, color = [green, blue, red, yellow]);
restart;
with(DETools);
ecdif := y(x)*diff(y(x), x) = -x - y(x);
soll := dsolve(ecdif, y(x), implicit);


cond_in := [y(0) = 1], [y(1) = 1], [y(0) = 3];
DEplot([ecdif], [y(x)], x = -1 .. 1, y = -3 .. 3, [cond_in], linecolor = blue);
restart;
with(DETools);
ecdif := diff(y(x), x) + y(x)*tan(x) = 1/cos(x);
soll := dsolve(ecdif, y(x));
y1 := unapply(rhs(soll), x, c__1);
plot([y1(x, 0), y1(x, 1), y1(x, 4)], x = -10 .. 10, color = [red, blue, green]);
restart;
with(DETools);
ecdif := diff(y(x), x) + 2*y(x)/x = x^3;
soll := dsolve(ecdif, y(x));
y1 := unapply(rhs(soll), x, c__1);
plot([y1(x, 0), y1(x, 1), y1(x, 5)], x = -5 .. 5, color = [red, blue, green]);
with(DETools);
ecdif := diff(y(x), x, x) + y(x) = sin(x) + cos(x);
soll := dsolve(ecdif, y(x));
y1 := unapply(rhs(soll), x, c__1, c__2);
plot([y1(x, 0, 0), y1(x, 1, 1), y1(x, 4, 6)], x = -5 .. 5, color = [red, blue, green]);
restart;
with(DETools);
ecdif := diff(y(x), x, x) - y(x) = exp(2*x);
soll := dsolve(ecdif, y(x));
y1 := unapply(rhs(soll), x, c__1, c__2);
plot([y1(x, 0, 0), y1(x, 1, 1), y1(x, 3, 4)], x = -5 .. 5, color = [red, green, yellow]);
restart;
with(DETools);
ecdif := diff(y(x), x, x) + 4*y(x) = 1/cos(2*x);
soll := dsolve(ecdif, y(x));
y1 := unapply(rhs(soll), x, c__1, c__2);
plot([y1(x, 0, 0), y1(x, 1, 1), y1(x, 3, 4)], x = -5 .. 5, color = [red, blue, green]);
restart;
with(DETools);
ecdif := diff(y(x), x, x) - diff(y(x), x) = 1/(1 + exp(x));
soll := dsolve(ecdif, y(x));
y1 := unapply(rhs(soll), x, c__1, c__2);
plot([y1(x, 0, 0), y1(x, 1, 1), y1(x, 4, 5)], x = -4 .. 4, color = [red, blue, green]);
restart;
with(DETools);
ecdif := diff(y(x), x) = 1 + y(x)^2;
cond_in := y(0) = 1;
soll := dsolve({cond_in, ecdif}, y(x));
y1 := unapply(rhs(soll), x);
plot(y1(x), x = -5 .. 5);
restart;
with(DETools);
ecdif := diff(y(x), x) = y(x)/(-x^2 + 1) + 1 + x;
cond_in := y(0) = 0;
soll := dsolve({cond_in, ecdif}, y(x));
y1 := unapply(rhs(soll), x);
plot(y1(x), x = -10 .. 10);
restart;
with(DETools);
ecdif := diff(y(x), x) - 2*y(x) = -x^2;
cond_in := y(0) = 1/4;
soll := dsolve({cond_in, ecdif}, y(x));
y1 := unapply(rhs(soll), x);
plot(y1(x), x = -5 .. 5);
restart;
with(DETools);
ecdif := diff(y(x), x, x) - 5*diff(y(x), x) + 4*y(x) = 0;
cond_in := y(0) = 5, D(y)(0) = 8;
soll := dsolve({cond_in, ecdif}, y(x));
y1 := unapply(rhs(soll), x);
plot(y1(x), x = 0 .. 1);
restart;
with(DETools);
ecdif := diff(y(x), x, x) - 4*diff(y(x), x) + 5*y(x) = 2*x^2*exp(x);
cond_in := y(0) = 2, D(y)(0) = 3;
soll := dsolve({cond_in, ecdif}, y(x));
y1 := unapply(rhs(soll), x);
plot(y1(x), x = -5 .. 5);
restart;
with(DETools);
ecdif := diff(y(x), x, x) + 4*y(x) = 4*(sin(2*x) + cos(2*x));
cond_in := y(Pi) = 2*Pi, D(y)(Pi) = 2*Pi;
soll := dsolve({cond_in, ecdif}, y(x));
y1 := unapply(rhs(soll), x);
plot(y1(x), x = -5 .. 5);
restart;
with(DETools);
ecdif := diff(y(x), x) - 1/2*y(x) = cos(x);
cond_in := y(0) = 1, y(0) = 2, y(0) = 3, y(0) = 4, y(0) = 5, y(0) = -1, y(0) = -2, y(0) = -3, y(0) = -4, y(0) = -5, y(0) = 0, y(0) = (-2)/5;
DEplot([ecdif], [y(x)], x = -5 .. 5, [cond_in], arrows = medium, linecolor = blue, stepsize = 0.1);
soll := dsolve(ecdif, y(x));
a__0 := -2/5;
NULL;
restart;
with(DETools);
ecdif := diff(y(x), x) + k*y(x)/x = x^3;
soll := dsolve(ecdif, y(x));
ecdif2 := diff(y(x), x) + y(x)/x = x^3;
cond_in := y(1) = 1, y(1) = 2, y(1) = 3, y(1) = 4, y(1) = 5, y(1) = -1, y(1) = -2, y(1) = -3, y(1) = -4, y(1) = -5, y(1) = 0, y(1) = (-2)/5;
DEplot([ecdif2], [y(x)], x = 0.1 .. 0.5, [cond_in], arrows = medium, linecolor = blue, stepsize = 0.1);

y1 := unapply(rhs(soll), x, k, c__1);
list_f := y1(x, 1, i) $ (i = -10 .. 10);
plot([list_f], x = -1 .. 1);
cond_in2 := y(1) = 0;
soll2 := dsolve({ecdif2, cond_in2}, y(x));
y2 := unapply(rhs(soll2), x);
plot(y2(x), x = -1 .. 1);
soll3 := dsolve({ecdif, cond_in2}, y(x));
y4 := unapply(rhs(soll3), x, k);
list_f2 := y4(x, i) $ (i = -3 .. 10);
plot([list_f2], x = -3 .. 3, y = -3 .. 3);
restart;
with(DETools);
ecdif := diff(y(x), x, x) - diff(y(x), x) - 2*y(x) = 0;
cond_in := y(0) = a, D(y)(0) = 2;
soll := dsolve({cond_in, ecdif}, y(x));
y1 := unapply(rhs(soll), x, a);
limit(y1(x, a), x = infinity);
limit(y1(x, -2), x = infinity);
NULL;
